# Generated by Django 3.2 on 2021-04-29 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='album_id',
            field=models.ForeignKey(default='a', on_delete=django.db.models.deletion.CASCADE, to='api.album', to_field='idd'),
            preserve_default=False,
        ),
    ]
