# Generated by Django 3.2 on 2021-04-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_track_album_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='artist_id',
            field=models.CharField(default='aaa', max_length=50),
            preserve_default=False,
        ),
    ]
