# Generated by Django 3.2 on 2021-04-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_track_artist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='tracks_url',
            field=models.CharField(default='aaaa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='tracks_url',
            field=models.CharField(default='aaa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='album_url',
            field=models.CharField(default='aaa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='artist_url',
            field=models.CharField(default='aaaa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='self_url',
            field=models.CharField(default='aaa', max_length=100),
            preserve_default=False,
        ),
    ]
